version: "3"
services:
  db:
    container_name: indiepair_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: indiepair
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - indiepair

networks:
  indiepair:
    driver: bridge
