version: "3"
services:
  db:
    container_name: mordern-nextjs-saas-starter_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mordern-nextjs-saas-starter
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - mordern-nextjs-saas-starter

networks:
  mordern-nextjs-saas-starter:
    driver: bridge
